### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Skillz4Killz** [Skillz4Killz/buncord#2]
This is the list of short-term requirements to get a working library together for 0.1.0

## Discord Server

- [x] Setup a GitHub feed #1 

## Rest

- [x] RestManager #3 
- [x] RestQueue extends Queue #3 
- [x] RestRequest #3 

## Gateway

- [ ] GatewayManager
- [ ] Shard
- [ ] GatewayQueue extends Queue

## Library

- [ ] Client

## Utils

- [x] Queue #3 
- [ ] Collection extends Map

## Typings

- [ ] Discord
- [ ] Buncord

## Unit Tests

- [ ] Local tests
- [ ] Integration tests

## CI

- [ ] Type check
- [ ] prettier
- [ ] linter
